### ISSUE TITLE
Modification in config.xml is needed in the repository

### ISSUE THREAD

**Issue by rickchoi** [m67hoff/MFPStarterIonic#10]
I think `<allow-navigation href="http://9.40.86.82:8100" />` needs to be removed and `<content original-src="index.html" src="http://9.40.86.82:8100" />` should be just `<content src="index.html" />`, without any hardcoded IP, to be used without any issue in other's environment.

**Comment by m67hoff** [comment]
Hy Rick, yes u are right -  the ip address is inserted / overwritten if running locally with livereload ( `ionic cordova run -l --emulator android`  or with `ionic serve`    (and sometimes I make the mistake and check this in)   - I will change it back - however, it also should work if (by mistake) the Ip is the file.
